packages:
  - .
  - docs
  - examples/*
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.11
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.11
engineStrict: true
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - corsa-oxlint
  - "@corsa-bind/napi"
  - "@corsa-bind/napi-darwin-arm64"
  - "@corsa-bind/napi-darwin-x64"
  - "@corsa-bind/napi-linux-arm64-gnu"
  - "@corsa-bind/napi-linux-x64-gnu"
  - "@corsa-bind/napi-win32-arm64-msvc"
  - "@corsa-bind/napi-win32-x64-msvc"
  - "@corsa-bind/napi-linux-x64-musl"
  - "@corsa-bind/napi-linux-arm64-musl"
  - "@oxlint/plugins"
  - oxlint
  - vite-plus
  - "@voidzero-dev/vite-plus-core"
  - "@voidzero-dev/vite-plus-darwin-arm64"
  - "@voidzero-dev/vite-plus-darwin-x64"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu"
  - "@voidzero-dev/vite-plus-linux-x64-gnu"
  - "@voidzero-dev/vite-plus-test"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc"
  - "@voidzero-dev/vite-plus-win32-x64-msvc"
onlyBuiltDependencies:
  - esbuild
useNodeVersion: 24.14.1
