name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24.14.1

      - name: Version bump
        id: version
        run: bash .github/scripts/version-bump.sh
        env:
          VERSION_TYPE: ${{ github.event.inputs.version }}

      - name: Get release notes
        id: release-notes
        run: bash .github/scripts/generate-release-notes.sh
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ steps.version.outputs.version }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          branch: release/v${{ steps.version.outputs.version }}
          delete-branch: true
          title: "Release v${{ steps.version.outputs.version }}"
          body: |
            ${{ env.RELEASE_NOTES }}
          commit-message: "chore: release v${{ steps.version.outputs.version }}"
          labels: |
            Type: Release
          assignees: ${{ github.actor }}
