name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.14.1

      - name: Version bump
        id: version
        run: bash .github/scripts/version-bump.sh
        env:
          VERSION_TYPE: ${{ github.event.inputs.version }}

      - name: Get release notes
        id: release-notes
        run: bash .github/scripts/generate-release-notes.sh
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ steps.version.outputs.version }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: release/v${{ steps.version.outputs.version }}
          delete-branch: true
          title: "Release v${{ steps.version.outputs.version }}"
          body: |
            ${{ env.RELEASE_NOTES }}
          commit-message: "chore: release v${{ steps.version.outputs.version }}"
          labels: |
            Type: Release
          assignees: ${{ github.actor }}
