name: main
on:
  push:
    branches:
      - main
      - eslint-cdk-plugin
  pull_request:
    branches:
      - main
      - eslint-cdk-plugin
    types:
      - opened
      - synchronize
      - reopened
      - closed

permissions:
  contents: read

jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@b5d848f5a62488f3d3d920f8aa6ac318a60c5f07 # v1
        with:
          node-version: "24.14.0"
          cache: true
      - name: Install dependencies
        run: vp install --frozen-lockfile
      - name: Build package
        run: vp pack
      - name: Run Unit Tests
        run: vp test --run
      - name: Run Integration Tests
        run: vp run test:integration
      - name: Run Vite+ Checks
        run: vp check
